# Generated by Django 4.2 on 2024-11-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance_app", "0003_transaction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction", options={"ordering": ["-date"]},
        ),
    ]
