# Generated by Django 4.2 on 2024-11-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance_app", "0004_alter_transaction_options"),
    ]

    operations = [
        migrations.AlterModelOptions(name="transaction", options={},),
    ]
